const RES = {
  statuses: [
    {
      created_at: "Thu Mar 23 18:19:07 +0000 2023",
      id: 1638968635602477056,
      id_str: "1638968635602477056",
      text: "@movistar_es @MovistarPlus Piratas, por no darme de baja me hicieron una oferta del 50% durante 6 meses y me llega\u2026 https://t.co/d2XYpNFIy9",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
          {
            screen_name: "MovistarPlus",
            name: "Movistar Plus+",
            id: 119938261,
            id_str: "119938261",
            indices: [13, 26],
          },
        ],
        urls: [
          {
            url: "https://t.co/d2XYpNFIy9",
            expanded_url:
              "https://twitter.com/i/web/status/1638968635602477056",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [116, 139],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1637773478865559552,
      in_reply_to_status_id_str: "1637773478865559552",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 286599021,
        id_str: "286599021",
        name: "ESHS",
        screen_name: "edsaher",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 48,
        friends_count: 201,
        listed_count: 0,
        created_at: "Sat Apr 23 09:28:05 +0000 2011",
        favourites_count: 8101,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 4904,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFF04D",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/286599021/1610046773",
        profile_link_color: "0099CC",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 18:18:52 +0000 2023",
      id: 1638968572285186067,
      id_str: "1638968572285186067",
      text: "@movistar_es Piratas, por no darme de baja me hicieron una oferta del 50% durante 6 meses y me llega la factura inc\u2026 https://t.co/845nh0nouK",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [
          {
            url: "https://t.co/845nh0nouK",
            expanded_url:
              "https://twitter.com/i/web/status/1638968572285186067",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1637806193816002562,
      in_reply_to_status_id_str: "1637806193816002562",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 286599021,
        id_str: "286599021",
        name: "ESHS",
        screen_name: "edsaher",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 48,
        friends_count: 201,
        listed_count: 0,
        created_at: "Sat Apr 23 09:28:05 +0000 2011",
        favourites_count: 8101,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 4904,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFF04D",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/286599021/1610046773",
        profile_link_color: "0099CC",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 18:18:29 +0000 2023",
      id: 1638968475308703744,
      id_str: "1638968475308703744",
      text: "@movistar_es Piratas, por no darme de baja me hicieron una oferta del 50% durante 6 meses y me llega la factura inc\u2026 https://t.co/WQlXNistoB",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [
          {
            url: "https://t.co/WQlXNistoB",
            expanded_url:
              "https://twitter.com/i/web/status/1638968475308703744",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1638861633375068161,
      in_reply_to_status_id_str: "1638861633375068161",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 286599021,
        id_str: "286599021",
        name: "ESHS",
        screen_name: "edsaher",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 48,
        friends_count: 201,
        listed_count: 0,
        created_at: "Sat Apr 23 09:28:05 +0000 2011",
        favourites_count: 8101,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 4904,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFF04D",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/286599021/1610046773",
        profile_link_color: "0099CC",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 18:18:09 +0000 2023",
      id: 1638968390315307024,
      id_str: "1638968390315307024",
      text: "@movistar_es @MovistarSeries Piratas, por no darme de baja me hicieron una oferta del 50% durante 6 meses y me lleg\u2026 https://t.co/dSK0hJwy1F",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
          {
            screen_name: "MovistarSeries",
            name: "Series en Movistar Plus+",
            id: 1951973071,
            id_str: "1951973071",
            indices: [13, 28],
          },
        ],
        urls: [
          {
            url: "https://t.co/dSK0hJwy1F",
            expanded_url:
              "https://twitter.com/i/web/status/1638968390315307024",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1638933623448518660,
      in_reply_to_status_id_str: "1638933623448518660",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 286599021,
        id_str: "286599021",
        name: "ESHS",
        screen_name: "edsaher",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 48,
        friends_count: 201,
        listed_count: 0,
        created_at: "Sat Apr 23 09:28:05 +0000 2011",
        favourites_count: 8101,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 4904,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFF04D",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/286599021/1610046773",
        profile_link_color: "0099CC",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 18:17:24 +0000 2023",
      id: 1638968201785516034,
      id_str: "1638968201785516034",
      text: "@movistar_es Piratas, por no darme de baja me hicieron una oferta del 50% durante 6 meses y me llega la factura inc\u2026 https://t.co/2UJvoKlfF4",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [
          {
            url: "https://t.co/2UJvoKlfF4",
            expanded_url:
              "https://twitter.com/i/web/status/1638968201785516034",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1638963826740678662,
      in_reply_to_status_id_str: "1638963826740678662",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 286599021,
        id_str: "286599021",
        name: "ESHS",
        screen_name: "edsaher",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 48,
        friends_count: 201,
        listed_count: 0,
        created_at: "Sat Apr 23 09:28:05 +0000 2011",
        favourites_count: 8101,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 4904,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "FFF04D",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1497283475677888516/nAn7yTHX_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/286599021/1610046773",
        profile_link_color: "0099CC",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 18:12:41 +0000 2023",
      id: 1638967013090422806,
      id_str: "1638967013090422806",
      text: "@movistar_es Con los 10MB de la fibra de la segunda residencia se queda corto para ver maratones de series no?",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: 1635982737835261952,
      in_reply_to_status_id_str: "1635982737835261952",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 261372916,
        id_str: "261372916",
        name: "Deiff \u2600\ufe0f",
        screen_name: "Davizzio",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 109,
        friends_count: 1306,
        listed_count: 0,
        created_at: "Sat Mar 05 20:41:24 +0000 2011",
        favourites_count: 3415,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 1307,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "C0DEED",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1551247334717153281/gJCjPKJ__normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1551247334717153281/gJCjPKJ__normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/261372916/1644941924",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 17:11:15 +0000 2023",
      id: 1638951554190286855,
      id_str: "1638951554190286855",
      text: "@movistar_es @MovistarSeries Sam y Frodo",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
          {
            screen_name: "MovistarSeries",
            name: "Series en Movistar Plus+",
            id: 1951973071,
            id_str: "1951973071",
            indices: [13, 28],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: 1638933623448518660,
      in_reply_to_status_id_str: "1638933623448518660",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 55804492,
        id_str: "55804492",
        name: "Luci MP",
        screen_name: "luttxia",
        location: "",
        description:
          "Adicta a las series y al aguacate. Vale, y a los realities",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 870,
        friends_count: 831,
        listed_count: 17,
        created_at: "Sat Jul 11 10:23:43 +0000 2009",
        favourites_count: 33532,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 19838,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "352726",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme5/bg.gif",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme5/bg.gif",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1600533455313506304/pdLzb-WU_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1600533455313506304/pdLzb-WU_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/55804492/1596577401",
        profile_link_color: "D02B55",
        profile_sidebar_border_color: "FFFFFF",
        profile_sidebar_fill_color: "99CC33",
        profile_text_color: "3E4415",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 16:34:50 +0000 2023",
      id: 1638942390856630279,
      id_str: "1638942390856630279",
      text: "@movistar_es Y lo mejor es que solo se me dice:\nEstamos pendientes del tema.\nQue poquito me queda",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 1220022993931374594,
        id_str: "1220022993931374594",
        name: "chema",
        screen_name: "Chemary2020",
        location: "Catalu\u00f1a, Espa\u00f1a",
        description: "\ud83e\udd2b",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 9,
        friends_count: 23,
        listed_count: 0,
        created_at: "Wed Jan 22 16:38:57 +0000 2020",
        favourites_count: 28,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 3,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
        profile_image_url_https:
          "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: true,
        default_profile_image: true,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 16:34:04 +0000 2023",
      id: 1638942195339108359,
      id_str: "1638942195339108359",
      text: "@movistar_es llevo 21 d\u00edas esperando cobrar el router que me mandasteis a coste 0 y por el cual me cobr\u00e1is 41\u20ac Todo\u2026 https://t.co/rXow42ZeVg",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [
          {
            url: "https://t.co/rXow42ZeVg",
            expanded_url:
              "https://twitter.com/i/web/status/1638942195339108359",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 1220022993931374594,
        id_str: "1220022993931374594",
        name: "chema",
        screen_name: "Chemary2020",
        location: "Catalu\u00f1a, Espa\u00f1a",
        description: "\ud83e\udd2b",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 9,
        friends_count: 23,
        listed_count: 0,
        created_at: "Wed Jan 22 16:38:57 +0000 2020",
        favourites_count: 28,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 3,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
        profile_image_url_https:
          "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: true,
        default_profile_image: true,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 16:25:48 +0000 2023",
      id: 1638940117879472132,
      id_str: "1638940117879472132",
      text: "@movistar_es @MovistarSeries Esperando con ansias! \ud83e\udef6\ud83c\udffc",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
          {
            screen_name: "MovistarSeries",
            name: "Series en Movistar Plus+",
            id: 1951973071,
            id_str: "1951973071",
            indices: [13, 28],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: 1638933623448518660,
      in_reply_to_status_id_str: "1638933623448518660",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 170246972,
        id_str: "170246972",
        name: "Lourdes \ud83d\ude07",
        screen_name: "livialourdes",
        location: "Cunit, Tarragona",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 127,
        friends_count: 159,
        listed_count: 3,
        created_at: "Sat Jul 24 09:05:26 +0000 2010",
        favourites_count: 35485,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 6325,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "ACDED6",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme18/bg.gif",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme18/bg.gif",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1634431324600561665/3-71XVgL_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1634431324600561665/3-71XVgL_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/170246972/1639502498",
        profile_link_color: "038543",
        profile_sidebar_border_color: "EEEEEE",
        profile_sidebar_fill_color: "F6F6F6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 15:25:32 +0000 2023",
      id: 1638924950059843585,
      id_str: "1638924950059843585",
      text: "@movistar_es hola, nos ha llegado una carta de Rectificaci\u00f3n de factura por impago, no entendemos muy bien a que vi\u2026 https://t.co/fsMjgWoItb",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [
          {
            url: "https://t.co/fsMjgWoItb",
            expanded_url:
              "https://twitter.com/i/web/status/1638924950059843585",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 1343280769003872257,
        id_str: "1343280769003872257",
        name: "Una Zorra bugueada \ud83c\udfae\ud83d\udc9c\ud83e\udd8a",
        screen_name: "Glitch_GamerFox",
        location: "Hatelia, Hyrule",
        description:
          "INFJ-T /21/Me gustan los videojuegos y me flipan los glitches. \ud83d\udc9aZelda\ud83d\udc9cPok\u00e9mon\ud83d\udcabShiny Hunt\ud83d\udc99Cuenta de arte \ud83c\udfa8: @shiyuarts",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 140,
        friends_count: 1040,
        listed_count: 1,
        created_at: "Sun Dec 27 19:41:45 +0000 2020",
        favourites_count: 64818,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 39625,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1608237654633504773/FqsZ5bnL_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1608237654633504773/FqsZ5bnL_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/1343280769003872257/1672268710",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 15:16:15 +0000 2023",
      id: 1638922615304892417,
      id_str: "1638922615304892417",
      text: "@movistar_es Ayer Ra\u00fal, hoy Emi, \u00bfhay alguien al mando ah\u00ed? Faltan por escribirme Darwin y Edison.",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: 1638814916537896968,
      in_reply_to_status_id_str: "1638814916537896968",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 308976798,
        id_str: "308976798",
        name: "Mariano Calabuig",
        screen_name: "marianocalabuig",
        location: "",
        description:
          "\ud83c\udfb6\ud83c\udfb6Con la gente que me gustaaa......\ud83c\udfb6\ud83c\udfb6\ud83c\udfb6 Madrid, Espa\u00f1a. Me dedico a lo mio, que es construir. A veces hablo en @Radiodecision y digo cosas.",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 1204,
        friends_count: 800,
        listed_count: 3,
        created_at: "Wed Jun 01 09:46:25 +0000 2011",
        favourites_count: 56798,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 26687,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "C0DEED",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme1/bg.png",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/3302917251/b8dcd83abcd7d2830d66a52a9e475399_normal.jpeg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/3302917251/b8dcd83abcd7d2830d66a52a9e475399_normal.jpeg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/308976798/1673966694",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 14:45:14 +0000 2023",
      id: 1638914809793052672,
      id_str: "1638914809793052672",
      text: "@movistar_es Recibido, gracias! Veo que mejor por aqu\u00ed que por tel\u00e9fono.",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: 1638912989255565312,
      in_reply_to_status_id_str: "1638912989255565312",
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 155532631,
        id_str: "155532631",
        name: "Hug! \ud83e\udd82\ud83e\udd82",
        screen_name: "hugprat",
        location: "Barcelona & Pened\u00e8s. Catalonia",
        description:
          "Padre de 2 fieras y amo de casa. Telecos y licenciado en comunicaci\u00f3n. \nCasteller en la reserva.\nFreelance.",
        url: "https://t.co/09KpfRL6Lc",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/09KpfRL6Lc",
                expanded_url: "http://file.cat",
                display_url: "file.cat",
                indices: [0, 23],
              },
            ],
          },
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 684,
        friends_count: 871,
        listed_count: 15,
        created_at: "Mon Jun 14 11:48:40 +0000 2010",
        favourites_count: 4367,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 2451,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "131516",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme14/bg.gif",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme14/bg.gif",
        profile_background_tile: true,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1395770957676040193/KmsnLGhm_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1395770957676040193/KmsnLGhm_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/155532631/1616595467",
        profile_link_color: "009999",
        profile_sidebar_border_color: "EEEEEE",
        profile_sidebar_fill_color: "EFEFEF",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "regular",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 14:45:00 +0000 2023",
      id: 1638914748996796416,
      id_str: "1638914748996796416",
      text: "@movistar_es gracias sois realmente",
      truncated: false,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 1573011118804680706,
        id_str: "1573011118804680706",
        name: "-_-",
        screen_name: "kick_dav1g",
        location: "",
        description: "W",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 3,
        friends_count: 97,
        listed_count: 0,
        created_at: "Thu Sep 22 18:08:07 +0000 2022",
        favourites_count: 61,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 8,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1573027135203278851/Gb82KxeB_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1573027135203278851/Gb82KxeB_normal.jpg",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
    {
      created_at: "Thu Mar 23 13:48:02 +0000 2023",
      id: 1638900411896610817,
      id_str: "1638900411896610817",
      text: "@movistar_es no es de recibo que cobr\u00e9is 14\u20ac por reemplazo de eSIM cuando sois vosotros los que no permit\u00eds transfe\u2026 https://t.co/5jfcejUPuV",
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "movistar_es",
            name: "Movistar Espa\u00f1a",
            id: 44992826,
            id_str: "44992826",
            indices: [0, 12],
          },
        ],
        urls: [
          {
            url: "https://t.co/5jfcejUPuV",
            expanded_url:
              "https://twitter.com/i/web/status/1638900411896610817",
            display_url: "twitter.com/i/web/status/1\u2026",
            indices: [117, 140],
          },
        ],
      },
      metadata: {
        iso_language_code: "es",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: 44992826,
      in_reply_to_user_id_str: "44992826",
      in_reply_to_screen_name: "movistar_es",
      user: {
        id: 168550882,
        id_str: "168550882",
        name: "Alejandro Heras",
        screen_name: "sampat4",
        location: "Madrid / Spain",
        description:
          "Hasta los huevos de la dictadura de lo pol\u00edticamente correcto y de esta sociedad de ofendiditos ergo un facha para mucha gente.",
        url: "https://t.co/YDDZ582VcZ",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/YDDZ582VcZ",
                expanded_url: "http://sampat4radar.blogspot.com.es",
                display_url: "sampat4radar.blogspot.com.es",
                indices: [0, 23],
              },
            ],
          },
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 352,
        friends_count: 386,
        listed_count: 2,
        created_at: "Mon Jul 19 17:57:59 +0000 2010",
        favourites_count: 18971,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 23392,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "0099B9",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme4/bg.gif",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme4/bg.gif",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1513121272338784256/W3H6WTeg_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1513121272338784256/W3H6WTeg_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/168550882/1664106238",
        profile_link_color: "0099B9",
        profile_sidebar_border_color: "5ED4DC",
        profile_sidebar_fill_color: "95E8EC",
        profile_text_color: "3C3940",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 1,
      favorited: false,
      retweeted: false,
      lang: "es",
    },
  ],
  search_metadata: {
    completed_in: 0.082,
    max_id: 1638968635602477056,
    max_id_str: "1638968635602477056",
    next_results:
      "?max_id=1638900411896610816&q=to%3Amovistar_es&include_entities=1",
    query: "to%3Amovistar_es",
    refresh_url:
      "?since_id=1638968635602477056&q=to%3Amovistar_es&include_entities=1",
    count: 15,
    since_id: 0,
    since_id_str: "0",
  },
};

export default RES;